import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2';
env.allowLocalModels=false; env.useBrowserCache=true;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const NAMES={zh:'中文',es:'Español',en:'English'};
let ready=false,running=false,stream=null,ctx=null,analyser=null,srcNode=null,timer=null;
let recorder=null,chunks=[],speech=false,silenceAt=0,segmentStart=0,queue=[],processing=false;
let asr=null,pipes={},scene='drilling',current={zh:'',es:'',en:'',source:''};
const glossary={drilling:[['testigo','岩芯','drill core'],['sondaje','钻孔','drill hole'],['poza de lodos','泥浆池','mud pit'],['plataforma','钻探平台','drill pad'],['profundizar','加深','deepen'],['desviación','孔斜','hole deviation'],['pirita','黄铁矿','pyrite'],['silicificación','硅化','silicification'],['vetillas','细脉','veinlets']],warehouse:[['stock de seguridad','安全库存','safety stock'],['consignación','寄售','consignment'],['orden de compra','采购订单','purchase order'],['almacén','仓库','warehouse']],maintenance:[['orden de trabajo','维修工单','work order'],['repuesto','备件','spare part']],safety:[['detener el trabajo','停止作业','stop work'],['evacuación','撤离','evacuation'],['derrame','泄漏','spill'],['talud','边坡','slope']],general:[]};
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function setProgress(p,t){$('#bar').style.width=Math.max(0,Math.min(100,p))+'%';if(t)$('#progressText').textContent=t}
function detect(text){if(/[\u3400-\u9fff]/.test(text))return'zh';let s=' '+text.toLowerCase()+' ';let es=[' el ',' la ',' de ',' que ',' para ',' por ',' una ',' un ',' con ',' pero ',' porque ',' está ',' tenemos ',' sondaje ',' almacén ',' seguridad ',' mantenimiento '],en=[' the ',' and ',' of ',' to ',' for ',' is ',' are ',' we ',' this ',' that ',' with ',' but ',' because ',' drill ',' warehouse ',' safety ',' maintenance '];let a=es.reduce((n,x)=>n+(s.includes(x)?1:0),0),b=en.reduce((n,x)=>n+(s.includes(x)?1:0),0);if(a===b)return/[áéíóúñ¿¡]/i.test(text)?'es':'en';return a>b?'es':'en'}
function sourceUI(l){['zh','es','en'].forEach(x=>{$(`#card-${x}`).classList.toggle('source',x===l);$(`#tag-${x}`).textContent=x===l?(x==='es'?'Original':'原文'):(x==='es'?'Traducción':'译文')});if(l)$('#micStatus').textContent=`🎙 当前识别：${NAMES[l]} · 会议监听中`}
function render(){['zh','es','en'].forEach(l=>{if(current[l])$(`#${l}`).textContent=current[l]});sourceUI(current.source)}
function esc(s=''){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function addHistory(){let h=$('#history');if(h.querySelector('.muted'))h.innerHTML='';let d=document.createElement('div');d.className='turn';let tm=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});d.innerHTML=`<div class="meta">${tm} · 原文：${NAMES[current.source]}</div><p><b>🇨🇳 中文</b>${esc(current.zh)}</p><p><b>🇵🇪 Español</b>${esc(current.es)}</p><p><b>🇺🇸 English</b>${esc(current.en)}</p>`;h.prepend(d)}
async function init(){if(ready)return;$('#loadModels').disabled=true;$('#engineStatus').textContent='正在初始化本地 AI…';try{let cb=x=>{if(x.status==='progress')setProgress(Math.min(95,x.progress||0),`下载/缓存模型：${x.file||''}`)};asr=await pipeline('automatic-speech-recognition','Xenova/whisper-tiny',{dtype:'q8',progress_callback:cb});pipes.zh_en=await pipeline('translation','Xenova/opus-mt-zh-en',{dtype:'q8',progress_callback:cb});pipes.en_zh=await pipeline('translation','Xenova/opus-mt-en-zh',{dtype:'q8',progress_callback:cb});pipes.es_en=await pipeline('translation','Xenova/opus-mt-es-en',{dtype:'q8',progress_callback:cb});pipes.en_es=await pipeline('translation','Xenova/opus-mt-en-es',{dtype:'q8',progress_callback:cb});ready=true;setProgress(100,'✅ 模型已缓存/就绪，无 API 费用');$('#engineStatus').textContent='✅ 免费本地模型已就绪';$('#talk').disabled=false;$('#loadModels').textContent='✅ 已初始化'}catch(e){console.error(e);$('#loadModels').disabled=false;$('#engineStatus').textContent='❌ 模型加载失败';toast(e.message)}}
async function tr(pipe,text){let r=await pipe(text,{max_new_tokens:256});return r?.[0]?.translation_text||r?.[0]?.generated_text||''}
async function translateAll(text){let l=detect(text);current={zh:'',es:'',en:'',source:l};if(l==='zh'){current.zh=text;current.en=await tr(pipes.zh_en,text);current.es=await tr(pipes.en_es,current.en)}else if(l==='es'){current.es=text;current.en=await tr(pipes.es_en,text);current.zh=await tr(pipes.en_zh,current.en)}else{current.en=text;[current.zh,current.es]=await Promise.all([tr(pipes.en_zh,text),tr(pipes.en_es,text)])}render();addHistory();speak()}
function speak(){let l=$('#speakLang').value;if(l==='off'||l===current.source||!current[l])return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(current[l]);u.lang=l==='zh'?'zh-CN':l==='es'?'es-PE':'en-US';speechSynthesis.speak(u)}
function newRecorder(){chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{if(chunks.length){queue.push(new Blob(chunks,{type:recorder.mimeType||'audio/webm'}));drain()}};recorder.start();segmentStart=performance.now()}
async function startMeeting(){if(!ready)return toast('请先初始化免费模型');if(running)return stopMeeting();try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});ctx=new (window.AudioContext||window.webkitAudioContext)();analyser=ctx.createAnalyser();analyser.fftSize=1024;srcNode=ctx.createMediaStreamSource(stream);srcNode.connect(analyser);running=true;speech=false;silenceAt=0;newRecorder();timer=setInterval(vadTick,100);$('#talk').classList.add('listening');$('#talk').textContent='■ 结束会议翻译';$('#micStatus').textContent='🎙 会议监听中，直接连续讲话…'}catch(e){toast('麦克风启动失败：'+e.message)}}
function vadTick(){if(!running||!analyser)return;let a=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(a);let sum=0;for(let v of a){let x=(v-128)/128;sum+=x*x}let rms=Math.sqrt(sum/a.length);let now=performance.now(),delay=Number($('#silenceDelay').value||1300);if(rms>0.025){speech=true;silenceAt=0}else if(speech){if(!silenceAt)silenceAt=now;if(now-silenceAt>delay && now-segmentStart>700){cutSegment();speech=false;silenceAt=0}}if(now-segmentStart>20000)cutSegment()}
function cutSegment(){if(!recorder||recorder.state!=='recording')return;recorder.stop();setTimeout(()=>{if(running)newRecorder()},80)}
async function stopMeeting(){running=false;clearInterval(timer);timer=null;if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());await ctx?.close().catch(()=>{});$('#talk').classList.remove('listening');$('#talk').textContent='🎙 开始连续会议翻译';$('#micStatus').textContent='🎙 会议已停止，剩余片段处理中…'}
async function drain(){if(processing||!queue.length)return;processing=true;while(queue.length){let blob=queue.shift();try{$('#micStatus').textContent=`🧠 正在处理会议片段… 剩余 ${queue.length}`;let ab=await blob.arrayBuffer();let audio=await decode(ab);let out=await asr(audio,{chunk_length_s:20,stride_length_s:3});let text=(out?.text||'').trim();if(text)await translateAll(text)}catch(e){console.error(e)}}processing=false;if(running)$('#micStatus').textContent='🎙 会议监听中，直接连续讲话…';else $('#micStatus').textContent='🎙 已停止'}
async function decode(ab){let c=new (window.AudioContext||window.webkitAudioContext)();let d=await c.decodeAudioData(ab.slice(0));let o=new OfflineAudioContext(1,Math.ceil(d.duration*16000),16000);let s=o.createBufferSource();s.buffer=d;s.connect(o.destination);s.start();let r=await o.startRendering();await c.close();return r.getChannelData(0)}
$$('.scene').forEach(b=>b.onclick=()=>{$$('.scene').forEach(x=>x.classList.remove('active'));b.classList.add('active');scene=b.dataset.scene;$('#sceneText').textContent='场景：'+b.textContent});
$('#loadModels').onclick=init;$('#talk').onclick=startMeeting;$('#translateText').onclick=()=>$('#textPanel').classList.toggle('hidden');$('#runText').onclick=async()=>{let t=$('#manualText').value.trim();if(!t)return;if(!ready)return toast('请先初始化模型');await translateAll(t)};$('#clear').onclick=()=>{current={zh:'',es:'',en:'',source:''};['zh','es','en'].forEach(l=>$(`#${l}`).textContent='');sourceUI('')};$('#copy').onclick=async()=>{let t=[...document.querySelectorAll('.turn')].map(x=>x.innerText).join('\n\n');if(!t)return toast('暂无记录');await navigator.clipboard.writeText(t);toast('已复制')};$('#clearHistory').onclick=()=>$('#history').innerHTML='<p class="muted">翻译完成后会保存在这里。</p>';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
